# Konfigurasi XRay untuk VPN SSH dengan TLS 1.2
inbounds:
- port: 4443
  protocol: vmess
  settings:
    clients:
    - id: 32d07a0b-8a46-4bcb-b5d5-72f29a91b3b5
      alterId: 64
  streamSettings:
    network: tcp
    security: tls
    tlsSettings:
      minVersion: tls1.2
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
  sniffing:
    enabled: true
    destOverride:
    - http
outbounds:
- protocol: freedom
  settings: {}
- protocol: blackhole
  settings: {}
